---
title: "Appendix. Ethnographic Sources"
author: "Cheng Liu"
date: "`r Sys.Date()`"
fontsize: 11pt
output: bookdown::pdf_document2
header-includes:
   - \usepackage{textcomp}
   - \usepackage{utopia}
   - \usepackage{lineno}
   - \usepackage{float}
   - \floatplacement{figure}{H}
   - \usepackage{caption}
   - \captionsetup[figure]{font=scriptsize}
   - \captionsetup[table]{font=scriptsize}
linestretch: 1.5
link-citations: yes
linkcolor: blue
bibliography: bibliography.bib
csl: apa.csl
---

# Africa

## Central Africa

### Barundi

Meyer, H., & Handzik, H. (1916). The Barundi: an ethnological study of German East Africa. Ott Spamer. p139. <https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=fo58-001>

"**The eldest son also inherits** the religious and professional attributes and **skills of his father**. If the father was a priest (kiranga), sorcerer, medicine man (umufumu), or **blacksmith** (umususi), etc., the eldest son becomes --- or remains --- in the same position or profession by inheriting from his father the insignia and tools, **in addition to the expert training**. Thus, certain professions remain the prerogative of certain families. If the mother is an expert of some sort, she will pass on her skills to her eldest daughter."

## Southern Africa

### Tanala

Linton, R. (1933). The Tanala, a hill tribe of Madagascar. In Publication 317. Anthropological series (Vol. xxii, p. 334). [s.n.]. p256-258. <https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=fy08-001>

"While I was in Ambohimanga the boys frequently brought me small models of traps which they had made. These were offered for sale and I doubt whether such models were used in their own play. **They begin to make real traps for small birds and mammals at a very early age**. Tanala toys seem to be characterized by an almost complete absence of replicas of things used by adults. I never saw any small figures of cattle or chickens, although such playthings are very common among the plateau tribes, or any miniature tools or utensils. The girls did not even have dolls."

### Tonga

Colson, E., & for Social Research, U. of Zambia. I. (1958). Marriage & the family among Plateau Tonga of Northern Rhodesia. Manchester University Press. p262-263. <https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=fq12-015>

"Today with the scarcity of game throughout most of the area, few receive training in hunting or fishing. **Other learning**, such as skill in constructing dwellings and granaries and in **making various tools or utensils, is fitted into the daily round and extends throughout childhood**, since it does not clash with herding duties as does field work."

## Western Africa

### Akan

Rattray, R. S. (Robert Sutherland). 1927. "Religion and Art in Ashanti." In . Oxford, England: Clarendon Press. p271-272. <https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=fe12-002>.

"In Ashanti, a generation or so ago, every stool in use had its own particular significance and its own special name which denoted the sex, or social status, or clan of the owner. The village of Afwia, a few miles from Coomassie, was the centre, in olden days, of the stool-carving industry. **Sons and sisters' sons were equally allowed to learn the art of carving, from father or uncle respectively**. Many of the stools shown here were the 'copyright' of the Ashanti king, and might not, on any account, be sold in the open market; 2 they were first given to the king, who would then present them to chiefs whom he wished to honour. **A woman might not carve a stool---because of the ban against menstruation**. A woman in this state was formerly not even allowed to approach wood-carvers while at work, on pain of death or of a heavy fine. This fine was to pay for sacrifices to be made upon the ancestral stools of the dead kings, and also upon the wood-carver's tools. If any wood-carver's wife was unfaithful to her husband, and the latter, being unaware of this, went to work, then 'his tools would cut him severely'. A wood-carver might not go to work leaving unsettled any quarrel or grievance with his parents."

### Igbo

Ottenberg, S. (1975). Masked rituals of Afikpo, the context of an African art. In Index of art in the Pacific Northwest (Issue 9, pp. 229, [8] leaves of plates). Published for the Henry Art Gallery by the University of Washington Press. p69. <https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=ff26-030>

"**Sometime after he was initiated, he started carving secret society masks**. His father had been a carver but had died long before Chukwu was old enough to learn from him. All of his father's masks had been destroyed in the fire during the British invasion of Afikpo in 1902. **Chukwu, then, combined his past experience at carving as an enna with what he learned from his older brother, who helped teach him**. **In fact, he had learned many of the primary techniques of mask carving (but not in wood or calabash) and of coloring when he was an enna.** Many boys at that time try their hand at the work. During that period he was unaware that his older brother, Oko, who was already initiated, was carving secret society masks, because members of the secret society do not reveal this fact to nonmembers, even in their own family. Similarly, his eldest brother did not know that Chukwu was making enna masks, for members of these enna groups are also secretive to outsiders about their activities. For the noninitiate, then, the stimulus to carve comes not from older persons---elders or professional carvers---but largely from the criticisms and rewards of age-mates. Chukwu's carving skills were basically learned when he was a child. When away from home in the Enugu area and at Makurdi, he apparently did no carving, but acquired considerable skill in the use of Western-type carpenter's tools, which undoubtedly contributed to his later success as a carver."

### Kpelle

Lancy, D. F. (1984). Work, play and learning in a Kpelle town. Xerox University Microfilms. p157-158. <https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=fd06-009>

**p157-158**

"**Certain tasks are quite complex and require training which could be called an apprenticeship**. These tasks include medicine making (Zo), leather-working, pottery, **blacksmithing**, and cloth weaving. Blacksmithing, at least, is learned during an apprenticeship. **Jawo-Gbala was apprenticed to his mother's brother. At first he only helped out on occasion by bringing wood for the forge and by operating the bellows. But even before this Jawo remembers sitting on a log at one end of the "shop" and watching his uncle work. At fourteen he began a formal apprenticeship which lasted three years.** His father "gave" him to his uncle, then, at the end of the apprenticeship, he "gave" him back to his parents. Jawo-Gbala first learned to make a knife blade, then a machete, later still ho learned to carve wooden handles and to forge the hoe and the adze. These latter two require bending the hot iron which must be done with care to avoid breaking it. His uncle made few comments while Jawo-Gbala was working, only when he had finished a tool would he give a critique. He wasn't allowed to keep a piece until it was perfect, nor could he make a machete until he'd mastered the knife, a hoe until he'd mastered the machete and so on. When he did make a mistake, or did sloppy work, his teacher would beat and berate him and order him to destroy what he'd made. During the apprenticeship, he paid his uncle through his work. He would make tools for people who would, in turn, agree to work on Kuu on his uncle's farm. The apprenticeship terminated when Jawo-Gbala had mastered all the tools including these needed in the actual blacksmithing and he set up his own forge."

**p177-178** (contexual information)

"**If one had a lot of time (say two years) to spend observing young children at Neé-pele, one would, I believe, record instances of all the important adult activities of the society**. Some other examples of Neé-pele that I did observe:

Children on the farm make their own Kuu. Boys sing and swing their sticks (= machetes) at the weeds. Girls cook dirt (= rice) in snail shells (= pots) over sticks the boys have fetched for the "fire."

A girl makes thread from pissava palm fibers (actually strips the fiber into threads rather than twisting it) which she winds onto a "bobbin." This she gives to a boy who has made a "loom" from bamboo sticks. He lays two sticks on the ground, parallel to each other to represent heddles, and moves his feet up and down as if to raise and lower them. Leaves or paper represent the woven cloth and this is divided up among the "children" for their "clothes."

**Boys play at blacksmith. Sticks represent the tools, the anvil is a rock and the tongs are a piece of bamboo that has been partially split along its length. Different types and sizes of sticks represent different hammers. The finished machete (a flat piece of wood) is given to its "owner" who goes off to cut brush with it.**

Many men from Gbarngasuakwelle have, at one time or another, gone down to the coast to work for a few months, for wages, in the Firestone rubber plantation. I observed insert_drive_file178 a seven year old boy with his younger brothers and sisters reenacting the homecoming scene of a worker returned from Firestone. He had made a carrier basket of palm thatch and proceeded to distribute to his "wife and children": dirt (= salt), leaves (= clothes), sticks (= shoes), rope (= belt), gourds (= pots) and cowrie shells (= money).

Several boys aged eight to ten practice palm-tree climbing, to "cut palm nuts." They play on a coconut tree which has a convenient curve in it not found in the oil-palm tree making it easier to climb the first few feet. Their Baling is a strip of bamboo which they loop around the trunk and hold at their sides."

Lancy, D. F. (1996). Playing on the mother-ground: cultural routines for children's development. In Culture and human development (pp. xii, 240). Guilford press. p89-90 <https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=fd06-031>

**p89-90**

"**Make-believe play** can provide opportunities for children to acquire adult work habits and to rehearse social scenes. In many cases the transition from play work to real work is nearly seamless. However, some adult roles are just too complex to be acquired solely in the course of Neé-pele---blacksmithing, for example.

Let us compare, briefly, the blacksmith at work in his forge with children doing a make-believe recreation of blacksmithing. In the realm of social relations, the blacksmith enters into a number of reciprocal relationships: between himself and a helper, who may also be an apprentice; between himself and a client, for whom he makes a tool and from whom he exacts an obligation to work on his farm; and and between his wife or wives who take care of many of his needs in return for his protection and maintenance. In the make-believe play we see these social relationships duplicated. **A boy of 8 or so is the blacksmith; two other boys of roughly the same age act as clients. A younger boy serves as helper, holding a "tool" for the "blacksmith" to "hammer" and fetching woodchips for the "fire." Finally, two girls, younger than 10, prepare and bring "food" for the smith to eat. The anvil is a rock and the tongs are a piece of bamboo that has been partially split along its length. Different types and sizes of sticks represent different hammers. The finished machete (a flat piece of wood) is given to its "owner," who goes off to cut brush with it.**

The "blacksmith" and his co-actors use the appropriate language in carrying out their make-believe. The older boy is addressed as "smith" or "old man," the helper as "boy" or "son." The girls as "wife." The specialized blacksmith's tools and paraphernalia are also referred to by their proper names.

The blacksmith possesses complex technical skills, the most important insert_drive_file90 of which is a basic understanding of metals and their reaction to various temperatures and stresses. **Clearly, these technical skills are not acquired to any appreciable degree during make-believe play. The blacksmith is also an important ritual figure and will be called on to assist in administering oaths. I found no evidence to indicate that children were learning the ideological aspects of being a blacksmith through their play.**"

**p61** (contexual information)

"**The blacksmith is the only skilled worker with a permanent workshop**. This is an open-walled building with a sharply pitched thatched roof. Inside, is a forge that consists of two earthen mounds separated by a narrow trough in which a fire of woodchips is laid. An assistant works two leather bags which force air through bamboo tubes down and out a small opening at the base of the fire. A large and smaller rock serve as anvils and the blacksmith uses a variety of hammers, punches, and tongs in his work. A customer brings both the iron and the wood to be made into the requested tool---a blacksmith does only bespoke work. **Formerly, iron, which is plentiful in the region, was smelted in local furnaces (Thomasson, 1987), but this practice has died out. Scrap iron is presently used**. Only old men knew the secrets of iron smelting and one had to be initiated into these secrets, as in the Poro."

**p154-155**

"**Akewoli-la was 16 when he learned to weave a hammock**; now he makes about 10 a year which he gives to friends. When he was 16 he saw a friend making a hammock. The friend asked Akewoli-la to help him, but Akewoli-la protested that he did not know how. **The friend offered to teach him, at no charge. In a week, Akewoli-la went off to make his own**. It was very good and when he showed it to his teacher, the man jokingly accused him of knowing how to do it all along. **Now Akewoli-la is teaching his son Tondolo (age 21) how to make a hammock. He teaches by demonstration, showing his son where to place and how to tie the knots.**

Tondolo was anxious to make his own and did successfully with only a few minor corrections by his father. He is now working on his second. **Every evening he spends about 2 hours twisting the fibers into twine and nearly has enough, after 2 weeks, to make the hammock**. Other hammock makers reported that they first made miniature hammocks before making a full size one. **Apparently these individuals began learning it at an early age, say, 12.** I surmise that they did not have the patience to prepare enough twine for a full-size one and were anxious to get into the actual hammock construction.

Lave and Wenger (1991) identified a cultural routine that fits the above cases very well---and also extends to apprenticeship (Chapter 9). They call this legitimate peripheral participation. Essentially, they have broadened the earlier conceptualization of Vygotskian theory. For example, the claim that all learning is social was taken to mean that learners would always be assisted by those who are more skilled---a claim the Kpelle material fails to substantiate. But there need not be an expert present to see the influence exerted by society on the learner. **In each of the previous cases, we see individuals acquiring weaving skills to enhance their own social participation.** As Sua indicates, if a girl wants to "look nice," to match the appearance of women, she must learn the skills to dress and decorate herself. In attempting to do so, she will be accorded the status of a "legitimate peripheral participant." She may be supplied with materials insert_drive_file155 and someone competent may agree to model the skill and also to critique the fledgling product. Miniature tools may be supplied. Overall, the society will treat these initial forays with respect---at worst, mild teasing is employed.

Westerman, D. H., & Schütze, F. (1921). The Kpelle: a negro tribe in Liberia. Vandenhoeck & Ruprecht; J. C. Hinrichs'sche Buchhandlung. p. 292B. <https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=fd06-007>

"**The technical teaching covers all skills: plaiting mats, weaving, basketry; making sieves, traps, fish nets, weirs; roofing, blacksmithing, hunting; carving dugouts, mortars and drums; making game boards**. Other requirements are: proficiency in games, in drumming and dancing, learning songs and folktales. Certain equipment, such as blacksmith tools and game boards, is made only in the bush and may therefore not be sold. A large part of the training period is taken up with sex education: "to handle women, to find the secret parts of women" [cited in English]; how to make women well disposed toward one, how to force them to obey, how to get behind their wiles and dodges and keep oneself unscathed. The pupils of the chieftain class are initiated into tribal life, its structure, the regulations about inheritance and the election of a new chief, the ceremonial at the king's court, the tribal traditions, relationships with neighboring tribes, warfare. The pupils in the class of religion are taught chiefly about medicine, magic and counter-magic, offerings, ordeals, sand-beating and other fortune-telling, about spirits, water-people and hill-people, forest devils, totem animals and plants and their treatment, about God. Naturally, everything worth knowing about the Poro Society itself and other secret societies is taught, especially the duties toward members and strangers. The pupils learn the secret characteristics and signs by which initiates recognize each other and can communicate unobtrusively, "and all kinds of tricks and rascality" [cited in English]. Instruction about sex is postponed until the later years when the boys reach maturity."

**p288** (contexual information)

"**Entrance to the Poro school takes place between the ages of seven and fifteen, rarely later. The complete course lasts four years.** During this time the pupils can learn everything that is taught in the Poro and reach the upper grades. Many, however, enter during the course and remain two or three years, one year, or even only a few months. Well-to-do people can shorten the training period of their children at will by means of gifts to the ˙namũ. Private lessons with a zō can also replace part of the stay in the bush, if one can prove, according to certain criteria, that one is an accepted member. It may even happen that a young man takes part only in the entrance ceremonies and is thus regarded as a member. This happens, for example, if a man, for some reason, has not attended the Poro, perhaps because he was away from home, but then wishes to get married and for this purpose must become a member.

A new Poro-bush is opened up at the beginning of the dry season, that is, from November on, when the field work of the year is completed. Entrance in the school and thus in the Society is nominally voluntary, but actually reluctant candidates are forced. Parents, with happy anticipation, wait for the time when their son can become a member of the Poro, and they gladly bear the trouble and costs involved, the long separation that is also painful for Negro mothers, and the dangers threatening their children in the bush. They will describe to their children, in harsh colors, the experiences awaiting them in the **bush**, the demands that will be made on them, and their privations, and will prepare them for dreadful things. At this time the ˙namũ with his retinue scours the villages and roads and where he finds an uninitiated one at the proper age he will take him along without further ado. His parents will later on find out only that the ˙namũ devoured him. If the ˙namũ happens to know that the women are absent, he will himself enter a hut and drag out potential shirkers. Often, the father, after arranging with the grand master, will send his boy on an errand and will let the unsuspecting one be caught along the way."

**p37** (contexual information)

"In southern Kpelleland, instead of earthen bowls and plates, wooden ones are used of various shapes and sizes. Imported brass bowls and iron pots are also used everywhere; vessels bartered in the North are also common. Other kitchenware to be mentioned are wooden spoons, most of them very artistically carved; gourd shells used for eating and drinking, for storing flour, rice, pepper; the long-stemmed ones are also used as spoons and as enema syringes. Likewise carved of wood are combs, sandals with leather straps, trumpets in the shape of elephant tusks, sword sheaths covered with leather, large mortars for rice and tubers, small ones for snuff, drums, game boards, masks, and dugouts. **It is difficult to find out exactly how these objects are made because they are produced in the schools of the secret societies,34 or at any rate the art is taught there and must therefore be kept secret.**"

### Tallensi

Fortes, M. (1938). Social and psychological aspects of education in Taleland. In *Memorandum* (pp. 64, 4 plates). Oxford University Press for the International Institute of African Languages and Cultures. p. 61. <https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=fe11-005>

"Boys, too, between the ages of 12 or 13 and 16 to 18 are at the stage of transition from childhood to young manhood. The imaginative play still prominent at the beginning of this period is given up by degrees and usually altogether abandoned when puberty is established. Like the adolescent girl, the boy of 16 or so finds his principal recreation in the dance at certain seasons. He, too, begins to frequent markets when time permits, for he is greatly preoccupied with the opposite sex, with courtship and flirtations and even transient love affairs, and there is no place like the market for pretty girls. An adolescent youth is already applying the deftness and skill acquired in juvenile play or in the arts and crafts of his boyhood to practical ends. **A 16-year-old takes an active part in building and thatching and in the manufacture of bow and arrows, or in the practice of crafts like leatherwork or the forging of tools and implements**."

### Yoruba

Lloyd, P. C. (1953). Craft organization on Yoruba towns. *Africa*, *Vol. 23*, 30--44. p. 33. <https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=ff62-009>

"The training of a young craftsman differs little in principle from that of the farmer's son. **A son is trained by his own father or, in the absence of his father, by his father's brother or his own elder brother. It is not uncommon for a boy to go to his mother's brother to learn the craft of his mother's patri-lineage**, for it is felt that the boy will have some craft blood in his veins. In the old days it was unlikely that a craftsman would adopt and train a boy unrelated to him. **Today, however, some blacksmiths do take boys who are strangers to the lineage, and pay apprenticeship fees to the master**. No man would ask a fee for training his sister's son. In most crafts there is work for a small boy---**he runs errands, pumps the smith's bellows, washes calabashes, sweeps the floor, winds cotton on to the reels**. **By watching his father he learns and by the time he reaches the age of sixteen he will have enough knowledge to perform most tasks and needs only a little practice**. By Yoruba law a father is expected to set up his sons in life---he must provide land, tools, and the first wife. The farmer gives his son a small plot of land on which the boy may work in the evening for his own gain (the work being known as ???); the father retains his right to the boy's labour during the earlier part of the day. Similarly the craftsman still expects his son to work for him; he will give him set tasks each day and only when these are completed may the boy work for his own gain. The father must provide bride-wealth for his son but the boy should earn pocket-money to pay the contributions to his social club (???), for presents for his girl friends and for his own luxuries. Whereas a farmer retains the labour of a son until marriage, the young craftsman tends to leave his father at an earlier age. There is no ceremony to mark the freedom of the boy although his tools would probably be ritually consecrated. After his freedom the boy will, of course, continue to live in his father's corner of the huge rectangular compound and he will probably eat with his parents until his marriage. His freedom gives him little enhanced status in the lineage where age, marriage, and the birth of children are the important criteria."

# Asia

## East Asia

### Okayama

Cornell, J. B. (1956). Matsunagi: the life and social organization of a Japanese mountain community. In Two Japanese villages: Matsunagi, a Japanese mountain community [by] John B. Cornell; Kurusu, a Japanese agricultural community [by] Robert J. Smith (pp. i–viii, xvii–xxiv, 113–232). University of Michigan Press. p.143-144. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=ab43-007

"Only two of the craft trades common throughout the nation (exclusive of the distinctively “mountain” skills called kobiki) are represented among occupations in Matsunagi: insert_drive_file144 carpentry and cooperage. **Carpentry involves more skill and knowledge than any other craft trade and commands most respect in the buraku**. While the carpenters of Matsunagi operate independently, they can easily join forces because they share a highly stereotyped body of skills. The carpenter, like other craftsmen, prefers to work close to home, in his own buraku, if possible. Like the sawyer, he uses a number of tools peculiar to his special handicraft. Among the most useful of these are saws, which are cruder and lighter than ours; he lays more emphasis on planes and adzes rather than on hammers and screw devices. Though rude by the standards of American building, the carpenter's craft produces a carefully mortised structure having great durability. Carpentry is also an informal confraternity sharing work ritual as well as common skills.

As the most prominent of the local trades, carpentry is outstanding among the forms of apprenticeship in the buraku. **A single master, if he is exceptionally skilled and experienced, may have as many as seven apprentices at once. But most masters have no more than two**, the eldest in point of service being called “older brother apprentice” and the others “younger brother apprentice.” Between these grows a bond of friendship like that between classmates or even between siblings, so that in later years they are inclined to turn to each other first for assistance in their trade. A carpenter wishing to apprentice his son is likely to ask his former “older brother apprentice” to take the youth. The apprentice spends much of his time with his master, even living as a member of the household during the seasons of greatest activity."

## North Asia

### Yukaghir

Jochelson, W. (1975). The Yukaghir and the Yukaghirized Tungus. In American Museum of Natural History, New York. Memoirs; The Jesup North Pacific Expedition. Publications: Vol. v. 13 (pp. xvi, 469 , [15] leaves of plates). AMS Press. p425. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=rv03-001

"**The Yukaghir blacksmith, Shalugin**, who lived on the Yassachnaya River, was looked upon by his tribesmen with great respect, and his art was regarded as a divine gift. Not everyone is fitted to learn** the blacksmith's trade. Among the Yukaghir, Yakut, Tungus and other Siberian natives, the status of the blacksmith is on a level with that of the shaman. **Shalugin was always worried because his elder son seemed unable to learn his father's vocation. “My people will be lost,” he once said, to me, “if my younger son should not be clever enough to become a smith.** Who will forge knives, axes and other tools for them, and who will repair their guns and lances?” Shalugin worked for the welfare of his clan, remuneration played quite a secondary role. He was satisfied with any reward and was not disturbed when a customer gave nothing. On the other hand, when he had to buy iron or steel blocks from traders or the government store he was assisted by his people. No one would withhold from him a fox or some squirrel skins to be used in exchange."

## South Asia

### Bengali

Klass, M. (1978). From field to factory: community structure and industrialization in West Bengal. Institute for the Study of Human Issues. p209-210. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=aw69-007

"And yet, having said all this, some Carpenter men go on to express a measure of sadness. Work in the factory is certainly well-paying, they note, but it is also dull and unsatisfying. An operator insert_drive_file210 performs a series of rote movements in any factory task—the same ones over and over, days without end. Whether one stamps out the bits of chain link, or assembles them, or assembles the fork in the frame, there is really very little satisfaction to be obtained after the first few days. It cannot compare with the pleasure of repairing a broken cart, or the deep satisfaction a man could feel when building a new one, working in the cool morning hours in the yard in front of his house with the children watching and neighbors walking by, joking and gossiping. **There was true pleasure, a Carpenter will say, in working with the tools he inherited from his father and in teaching his sons the ancient trade. Now the boys are not interested in learning to become carpenters, for they—like their fathers—hope they will go to work in the factory. And, after a hard day's work, who has time to teach the boys?** In many Carpenter homes, the tools are rusty and neglected. And yet, say the men who have made all the foregoing remarks, it cannot be denied that the factory wages are excellent, and no one in his right mind would choose the chancy and inadequate income of a village carpenter over the factory wages…."

## Southeast Asia

### Ifugao

Lambrecht, F. (1958). Ifugaw weaving. Folklore Studies, Vol. 17, 1-53 , plates. p1. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=oa19-023

"**Weaving, from cotton to cloth, is the exclusive task of women**. They weave for themselves and the members of their family, but only occasionally for selling purposes. **Girls learn how to weave by helping their mother or elder sister, for example in putting up the warp (see infra), and by actual practice under the latters’ supervision: most of them become quite skilled within a short period of time.** The weaving tools, i.e., the loom sticks, the spindle, the apparatus for fluffing, skeining and winding, are, of course, made by the men."

### Semai

Dentan, R. K. (1978). Notes on childhood in nonviolent context: the Semai case. In learning non-aggression (pp. 94–143). Oxford University Press. p.126. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=an06-016

"Acquiring skills. Besides being coercion that might make the child sick, **training is unnecessary because “our children learn by themselves” (see “Enculturation” above). Children tag along after adults, especially parents or grandparents, imitating their activities in ways that shade imperceptibly into helping out. Seeing the child's interest or in response to its initiative, the adult may show insert_drive_file127 it how to do something better or may make a small version of the appropriate tool. When no adults are around, children often play at adult activities by themselves.**"

### Vietnamese

Hickey, G. C. (1964). Village in Vietnam. Yale University Press. P165-166. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=am11-173

"**The usual pattern is for carpenters and implement makers to pass on to their sons the skills of the trade** as well as the tools—saws of various sizes, chisels, planes, bow-powered drills, hatchets, squares, metal rulers, plumb lines, pliers, and hammers. **One exception was a carpenter in Ap Dinh-B who, because his son lacked propensity for the trade, took one of his brother's insert_drive_file166 sons as an apprentice, later accepting him as a full partner. Some young men complained that there is a tendency to accept only kin as apprentices**, and they cited the example of a young laborer who was unable to become an apprentice in the village, so he learned carpentry working in a Tan An lumberyard."

# Middle America and the Caribbean

## Central Mexico

### Nahua

Lewis, O. (1951). Life in a Mexican village: Tepoztlán restudied. University of Illinois Press. p.98. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=nu46-002

"The division of labor according to sexes is clearly delineated. Men are expected to support their families by doing all the work in the fields; by caring for the cattle, horses, oxen, and mules; by making charcoal and cutting wood; and by carrying on all the large transactions in buying and selling. In addition, **most of the specialized occupations, such as carpentry, masonry, and shoemaking, are done by men. An important function of the father of the family is to train his sons in the work of men**. When a Tepoztecan man is at home, his activities consist of providing the household with wood and water, making or repairing furniture or work tools, making repairs on the house, and picking fruit. Men also shell corn when shelling has to be done on a large scale. Politics and local government, as well as the organization and management of religious and secular fiestas, are also in the hands of the men."

### Zapotec

Cook, S. (1979). Teitipac and its metateros: and economic anthropological study of production and exchange in a peasant artisan community in the valley of Oaxaca, Mexico. University Microfilms. p.183-191. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=nu44-028

**p189-191**

"c. Enculturation. The task of the present section is to ascertain the function of kinship in the process of metatero enculturation in the Teitipac villages. **In San Sebastian the finishing tasks in metate and mano production are taught in the residence lot; all preliminary and intermediate production tasks are taught and learned on location in the quarries.** In San Juan, on the other hand, where the quarries are close to the village and more accessible than those in San Sebastian, metate size blocks of stone (trozos) are often carted from the quarry to the metatero's residence lot in the village. Thus, the residence lot is, in many instances, the San Juan metatero's workshop.

**The apprentice in both villages is taught by instruction from more skilled metateros — the instruction assuming the form of tips and pointers volunteered periodically rather than systematically programmed training. Much of what any apprentice learns is on his own initiative through trial and error or imitation. The San Juaneros, unlike the San Sebastianos, often congregate on street corners in groups of five or six to ‘finish’ (Iabrar) their metate products. In this informal street corner setting a spirit of friendly insert_drive_file190 competition prevails which is conducive to the development or perfection of production techniques.** As one San Juanero describes this situation:

And after I was able to make metates, we would meet on the corner to finish them. Well, there they taught me how to do a better job of finishing them — Guillermo Cruz, who's now dead, was my maestro. There we competed with each other — with our other companions — to see who could finish the best product. Well, of course, with patience we turned out well made products.

**Only one of 24 metatero informants in San Sebastian claims to have had no teacher; eleven state that their father was the chief agent in their occupational enculturation; three learned from affines and one from an elder brother. The remainder were taught by non-relatives, two maestros being responsible for training four of them. Of 15 San Juan informants, 7 were taught by their fathers, two by mother's brothers, one by his elder brothers, and another by his Fa-SisHu. Four of these informants were taught by non-relatives as apprentices in quarries owned by their maestro-patrones. In sum, then, kinship ties between teacher and apprentice are basic to the process of metatero enculturation.**

What are the principal aspects of this process? **During his period of apprenticeship the apprentice is economically dependent on his maestro-patrón; he helps the latter in those quarry tasks which require a minimum of skill but much effort (e.g., carrying waste stone out of the quarry) and is rewarded by an occasional piece of stone, access to his maestro's tools, and with advice or informal instruction.** The insert_drive_file191 only source of remuneration for the apprentice is the revenue from the sale of his output — which is usually small in quantity and poor in quality. Inevitably, then, for a period of several weeks or months the pecuniary reward for the apprentice's efforts is minimal and he must rely on patience and perseverance (and deferral of gratification) to get him through his apprenticeship."

**p183-184** (contexual information)

"The informal organizational structure of the Teitipac metateros consists of three functionally differentiated and ranked sets of status whose internal relationships are schematized in Figure 13. The maestros (masters or teachers) or dirigentes (directors) are capable of organizing and directing quarry operations, of instructing, and are the most skilled insert_drive_file184 quarrymen and metate makers. The mozos metateros are those members of the occupation who lack the knowledge and experience to organize and direct quarry operations but are competent makers of metates and manos. **Apprentices, who are mostly boys and young men under the age of 25, can neither organize and direct quarry operations nor make metates. They are teaching themselves by trial and error and by imitation, or are being taught by more skilled workmen, to make metate products.**

Since it is very difficult for a neophyte to learn to make metates on his own, he must undergo a period of ‘on the job’ training. Consequently, the informal status hierarchy represented in Figure 13, looked at diachronically, indicates developmental stages in the metatero's career. This is not to imply that all apprentices become full-fledged metateros nor that all metateros become maestros but, rather, that those who do attain higher ranks passed through the lower ones."

**p185-188** (contexual information)

"As the highest status in metatero organization, that of maestro merits further discussion. Table 8 contains a tabulation of the traits most emphasized in 15 metatero definitions of maestro. Below is a sampling of some of these definitions:

1. He's a maestro because he knows how to do it. He knows how to make metates and manos. Also he can make ‘carved design’ (calado y dibujado) metates. He knows the work from the beginning — the cutting of stone in the quarry. Not everyone does that well. That's a maestro.

2. The maestro has the quality of saying how one is going to blast and cut stone in the quarry. He can even say — as if he were divining the stone — how many metates a block of stone will yield. That's a maestro; he is a director. The worker who doesn't know how to cut stone asks advice from the maestro in his quarry. The maestro tells him: ‘That stone should be cut like this’.

3. The one who turns out the best work is a maestro. In every sense he knows stone. He can appraise stone in the quarry. Just by looking at stone in the quarry he can estimate how many metates will come out of it.

It is clear from these statements and from the table that there is a broad consensus among the metateros as to what constitutes a maestro — the 3 salient traits being skill in appraising and cutting stone, skill in the manufacture of metates, and ability to organize and direct quarry operations. The term maestro, then, connotes ‘master’ — a status whose artisan occupant excels in his understanding and application of the strategy and tactics of his craft.

b. Recruitment. **The typical metatero career is initiated between the ages of 10 and 20 years, with the mean starting age of a sample of 35 informants being 17 1/2 years.** Recruitment into the occupation tends to be through ascription. Of 30 active metateros censused only four reported having no consanguineal relatives in ascending generations who were metateros. Of the remaining 26, 16 reported a three-generational patrilineal continuity in the occupation (i.e., from FaFa or FaFaBr to Fa or FaBr to EGO). Direct three-generational patrilineal succession (FaFa to Fa to EGO) occurred in 14 of these cases, with direct two-generational patrilineal succession (Fa to So) occurring in the other two. A total of 13 of these informants have metateros in both their matri- and parti-lines in at least one ascending generation; however, occupational succession has a definite patrilineal bias.

Only four of these 30 informants do not have consanguineal relatives of the first or second degree who are active metateros. All of the others have either first or second degree consanguines (in most cases both) who are active members of the occupation. Moreover, all of the informants have affines who are practicing metateros. Some idea of the complexity of the consanguineal and affinal networks among the metateros can be provided by tracing these relationships for one metatero as is done in Table 9.

Certain families in the Teitipac villages are known as metatero families. For example, it is often said of such families: “Son del oficio desde sus abuelos y bisabuelos” (They have been in the occupation since their grandfathers and great-grandfathers). Such reputations are, indeed, supported by the genealogical facts. For example, the Cruz family in San Sebastian is known as a metatero family. The genealogy of the direct male descendants of Jose Cruz, the progenitor, is represented in Figure 14.

As it turns out, all 14 of the direct male descendants of Jose were or are metateros. Since Jose was himself a metatero his occupation has been transmitted through a total of 3 descending generations. Between the Cruz and three other patrilines in San Sebastian society, the metatero population has a deep and extensive kinship base."


**p192-193** (contexual information)

"There are variations in the recruitment and enculturation process as can be inferred from the following account by a San Juanero of how he became a metatero:

From the beginning I was a peasant. But in 1933 one of my compadres, Efren Carranza, introduced me to the occupation. He said to me: ‘Compadre, if you want to learn I will teach you; give me a peso to buy you a handpick so that you can begin to make manos’. I gave him the peso and with it he bought me a little hammer — second hand — I remember. And with that second hand hammer he went to Jose the blacksmith who made two picks from it. Until this day I remember that Jose charged me $1.50 for those two picks. And the day that he finished making those tools, I went to pick them up very contentedly and, then, went to see an old metatero named Manuel Cruz. Manuel sold me some pieces of stone, some unfinished manos, for 5 each; and on that first day I finished a mano. I returned to my house very pleased with myself because I had gone to the house of Sr. Cruz so that he could teach me. However, I was somewhat pensive as well because, on that first day, a little piece of stone got into my eye; that night I sawinsert_drive_file193 little lights and I said to myself: ‘What will I do to protect my sight’? But that week I finished 6 manos and we went to Oaxaca to sell them. There I bought myself a pair of dark glasses which I've worn ever since to protect my eyes.

Little by little I began to make 1 mano daily, then, 3 ever 2 days. Afterwards I was making 2 daily. That was enough because in those days a laborer earned only 25 from sunrise to sunset — a hard day's work; I was able to go to the fields to bring alfalfa for my animals and then by 6 in the afternoon finish 2 manos; that gave me an income of 50 daily.

I began to make metates without a maestro; I observed how others did the work and then I made some wooden models — tracing the form from an old metate. Then, I began to cut stones using a ruler and a pencil to mark the cuts. I started using a little chisel — about 15 centimeters long — and slowly but surely I perfected my finishing techniques. In 1939 I began to make specially decorated metates (carved in bas relief) — those that sell for 200 pesos each now and then were worth only 8 pesos.

In San Juan one observes more young boys working in the metate industry than in San Sebastian. Many young San Juaneros (some as young as 8–10 years) wander through the quarries picking up discarded pieces of stone (“pepenando la piedra”) unsuited for making full-size metate products but which are suitable for making small metates and manos which are sold as toys. Many of these boys have made agreements with village traders for the sale of their products. By the time they reach their teens, many of these San Juan youths are skilled stone cutters and have only to gain experience in the quarries to qualify as full-fledged metateros."

# North America

## Arctic and Subarctic

### Kaska

Honigmann, J. J., & Bennett, W. C. (1949). Culture and ethos of Kaska society. In Yale University publications in anthropology (Issue 40, pp. 366, 12 plates). Yale University Press. p.185-186. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=nd12-001

"Education. **Most education for living is received by the child in the course of performing routine activities. Such education is unformalized and undirected.** Our characterization above of the training of dogs reflects some of the features of the child's education. Instruction and direction are rarely explicit. “Do this,” is the formula, and the child is left with the task of working out the details of an activity for himself. If the young girl is asked to make a fire and tries to light large pieces of wood without first splitting kindling, the task will be taken over by an adult. The child may then observe the correct sequences for the completion of the activity, but few people trouble to drill these into the learner. **Sometimes generalized instructions are furnished to children who, in carrying these out, often become confused.** Thus we observed one fourteen year old girl make tea by putting the leaves into cold water. Nobody referred to the muddy quality of the beverage. The same kind of teaching was used with the ethnographer. **Activities were illustrated but never explained in detail, the exposition of principles being ignored.** On the second day of a journey with dog team and toboggan, the handling of the vehicle was entrusted to the ethnographer without a word of instruction regarding the technique of managing the dogs. Meanwhile the guide walked on ahead, rapidly breaking trail, so that when the traces fouled and the dogs rebelled, he had to retrace almost an eighth of a mile. **Another observation that is worthwhile making so far as education is concerned, deals with the relatively narrow range of stimulation available to children, particularly in winter, when youngsters lacking toys are confined to small cabins and rarely interact with parents.**

The girl's education is derived from her household duties and begins quite early. From the age of six or seven, she hauls water and packs wood. A few years later she learns to cut and sew moccasins, often practicing with scraps of moosehide; tends the rabbit snares; cuts wood; washes clothes, and helps with simple cooking—all by following the examples of her mother or older sisters and with a minimum of verbal instruction. A young girl may at first rebel at economic chores and seek to shirk them, but by the time she is nine or ten years old the rebellion has almost totally disappeared and she is only anxious to complete her duties quickly so as to have free time available. **Boys' education begins somewhat later, at the age of eight. Now they begin to accompany fathers or older brothers on short fishing, hunting, and trapping trips. The boy learns masculine skills by observing older men prepare snow-shoe frames, hew lumber, or manufacture implements, vehicles, buildings, and tools.** While the boy assists older men in these activities, by collecting firewood and handling tools, his real economic contribution begins much later than the girl's. Not until he is near puberty, does the boy begin to manufacture apparatus on his own or go out to hunt large game with an agemate.

As early as the age of three, a child begins to try using snowshoes. Such learning is insert_drive_file186 gradual, but by six the child is already able to cover ten or more miles with these travel aids. Children begin to feed themselves at about three years of age."

## Eastern Woodlands

### Natchez

Lorenz, K. G. (Karl G. (2020). Culture Summary: Natchez. Human Relations Area Files. p.10. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=no08-000

"From birth, all children’s heads were flattened for aesthetic reasons, with a plank attached to their cradleboard. By age three, all children began to learn how to swim. **Both boys and girls lived work-free lives until around age twelve, when each gender began to help out the same gender parent and learn particular skills. Girls learned to grind maize, gather firewood, tend the fire, and to make pottery, mats and animal skin clothing. Boys, like men, are said to have worked far less around the village than the women and girls; they instead focused on tasks beyond the village, such as hunting, fishing, cutting firewood, and making tools and weapons.** After puberty, both young men and woman were encouraged to engage in premarital sex. If a pregnancy should occur, the young woman’s parents would help to raise the child if their daughter wished to bear and keep it. If not, then the infant would be strangled outside the house and buried with little fanfare."

## Northwest Coast and California

### Nuu-Chah-Nulth

Kenyon, S. M. (1980). The Kyuquot way: a study of a West Coast (Nootkan) community. In Mercury series Paper - Canadian Ethnology Service; Diamond Jenness memorial volume (Issue 61, pp. xviii, 180). National Museums of Canada. p. 82. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=ne11-022

"**The young men who have begun to carve within the last few years often learned the art as children from their fathers or uncles**. They have started to use their knowledge as they come to realize the potential market for genuine Indian goods. They have the tools from their childhood (of limited range, often only a short-bladed knife and a chisel) and have gone to **libraries in Campbell River and Victoria to study pictures of old works of art**. Gradually they are building up their own folders of designs for painting, carving and engraving."

### Quinault

Storm, J. M., & Capoeman, P. K. (1990). Land of the Quinault. Quinault Indian Nation. p.54. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=nr17-006

"**Several families together were also a more efficient unit for education. Children would be exposed to that much more basket weaving, tool making, blanket weaving, carving, and so forth in a house with many adults and older children.** Since grandparents were the main babysitters and educators, one grandparent could take care of all the grandchildren together without anyone having to move to some other place. This freed all the younger adults for their endless outdoor jobs."

### Tillamook

Sauter, J., & Johnson, B. (1974). Tillamook Indians of the Oregon coast. Binsfords & Mort. p.32-34. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=nr21-005

"**Model canoes, small bows and arrows, miniature war clubs of whale bone, and diminutive fish spears all reflected his training**, Feats of personal discipline and courage were used for his childhood training. Swimming in rough water for long periods, running up steep hills, rubbing his body with nettles, and adventuring into the forest at night were but a few of the tasks assigned by the tribal elders.

**A small girl underwent similar training, only hers stressed perseverance, not courage. She was taught the art of food gathering and preparation and the important task of making tools out of the many types of mammal bones present in the villages. She also learned the basket-weaving art of the Salish insert_drive_file34 tribes,** recognized as one of the finest weaves of all the Indian tribes of the Americas. She learned to gather clams in freezing water, to dig for roots in muddy swamp areas, and to gather fruits and berries and wood. She was also schooled in home-making, sewing, matmaking, and most enjoyable of all, personal grooming."

Skoggard, I. A. (2022). Culture Summary: Tillamook. Human Relations Area Files. p.4. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=nr21-000

"The practice of using a cradle board to flatten the foreheads of babies distinguished all freemen. At six years old, the parents held a naming ceremony, which involved ear piercing for boys and girls. They were named after deceased relatives. **Gendered activities were taught at an early age. Boy’s toys included canoes, bows and arrows, and war clubs. Girls were taught to gather food, weave baskets, and make bone tools**. Corporal punishment was rare. Moral tales about the fate of bad people were told around the hearth in the evening. An important stage in the life cycle for young men and women was acquiring a guardian spirit, under the tutelage of a shaman. Boys in their early teens went out alone into the forest to fast, hoping to find a spirit associated with the career they desired, that of a hunter, shaman, or warrior. They would not declare their spirit until the winter ceremony. At her first menstruation a young woman was secluded in a hut. During this time women would fast and seek a guardian spirit chaperoned by a female shaman. A woman married soon after her first menses."

## Plains and Plateau

### Assiniboine

Denig, E. T., & Hewitt, J. N. B. (John N. B. (1930). Indian tribes of the upper Missouri. Government Printing Office. p.520. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=nf04-005

"The domestic government is exercised by both father and mother. As long as the child is small the mother has the sole charge of it, but when it begins to speak the father aids in forming its manners. If a girl, he makes toy tools for scraping skins and the mother directs her how to use them. **She also shows her how to make small moccasins, etc. Their first attempts in this way are preserved as memorials of their infancy.** When a little larger, the scale of operations is increased and sewing, cooking, dressing small skins, and garnishing with beads and quills are taught, together with everything suitable for a woman's employment. If the child be a boy the father will make it a toy bow and arrow, wooden gun, etc.

When a little larger he will give him still stronger bows and bring unfledged birds into the lodge for his son to kill. Larger still and he runs about with a suitable bow after birds and rabbits, killing and skinning them. Another stage brings him to learn the use of the gun, to ride, approach game, skin it, etc., all of which is taught him by his parent. The rest he acquires from the time and facility their manner of life affords for practicing these pursuits, and at the age of 17 or 18 makes his first excursion in quest of his enemies' horses."

### Blackfoot

Ewers, J. C. (1945). Blackfeet crafts. In Indian handcrafts (Issue 9, p. 66). United States Indian Service. p.29. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=nf06-041

"Elderly Blackfeet say that quillwork was regarded as a sacred craft by their people. **Girls or young women were taught the craft by the older women. First the younger women were initiated ceremonially into the art of handling the sharp-pointed quills. It was claimed that women who attempted to do quillwork without having first experienced this ceremony would surely “go blind” or suffer from a swelling of the finger joints. Then they were taught how to use the tools of the quillworker’s craft and how to employ the various methods of quill sewing, plaiting and wrapping known to their elders.** Quills of the same size in assorted colors were kept in long, cigar shaped, bladder containers until ready for use. The quillworker’s kit also included one or more bone or metal awls for making holes in the skin, a quantity of sinew thread for passing through these holes in attaching the quills to the surface of the skin, and a bone or horn instrument for pressing and flattening the quills after they had been sewn to a flat surface. The Blackfeet quillworker held quills in her mouth to soften them, then flattened them between her teeth and put them in place at once. It was customary for a beginner to give her first piece of quillwork as an offering to the sun."

## Southwest and Basin

### Navajo

Adair, J. (1944). The Navajo and Pueblo silversmiths. In Civilization of the American Indian series (pp. xvii, 220). University of Oklahoma Press. p.89-91. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=nt13-090

“In regions like Zuñi, Smith Lake, and Manuelito, the traders keep the smiths busy with orders for the greater part of the year. The more silver a smith can turn out, the greater his income; therefore, **it is to his economic advantage to teach the art not only to his sons, but also to his daughters and his wife**. They will increase the family income in direct proportion to the amount of silver they make. Women whose husbands make only a small amount of silver are not apt to learn the art.”

“If a Navajo learns how to make silver from a relative, he does not pay for his instruction. **He asks a relative to teach him to make silver, and in return he assists the master smith with his work.** The [90] advantages are mutual—the apprentice learns a craft which will yield an income to him in the future, and while he learns, the experienced smith is enabled to increase his own income by turning out more silver. Or, to state this the other way around, the experienced smith asks one of his relatives to help him with his work, and in return for this help, he is willing to teach the craft to the assitant. This state of affairs exists in the regions where silver has been extensively commercialized and where a smith needs help with his work. In fact, such smiths often retain the services of their apprentices after they have gained skill in the art. **A smith is considered skilled in the craft when he has mastered the art of soldering.** Charlie Bitsui paid Francis Yazzie ten dollars a month for helping him. Peter Roans learned from his cross-cousin, John Hoxie, and when he became skilled, he was given money enough to buy clothes at the post, and in addition scrap silver and turquoise. Suski helped his father, Chai Begay, and in return his father made occasional gifts of small amounts of money.”

**The novices often work for a master smith for several years**. In the meanwhile, they save their money and buy their own tools. **It is often two years, and sometimes longer, before a smith has a sufficient number of tools to set up his own shop and work independently.**

“Many silversmiths have learned the craft just by watching other smiths at their work. When I asked Charlie Houck from whom he had learned the art, he replied: ‘No one taught me, I just learned myself. I watched other fellows make silver, then I went [91] ahead and made some myself. I was able to do everything but solder and I learned how to do that from Red Mexican.’ **Many smiths have learned the art in just that way, with no formal instruction of any sort, but it is considered dishonest if one smith watches another without telling him that he wants to learn.** I asked Atsidi Yazzie how he learned. He said: ‘I didn't learn from any one person. I just picked it up by watching different smiths at work. I stole the art from some of those smiths. I watched Atsidi Chon make silver, but he didn't know that I was learning while I was watching him. Then when he went away for a day or so I would go over to his hogan near Klagetoh and use his tools and solder to make some buttons and other things out of my own dimes and quarters.’”

**p73-76** (contexual information)

"After the silver had cooled for about ten minutes, Tom told me that it was ready to pound. Gripping one end of the bar with pliers, I held the bar over the anvil and pounded down on the metal. I had given it just two blows with the hammer when the silver flew out from the pliers and landed three feet away. Tom laughed. I hammered once more. Tom instructed me to strike the blows at an angle so that the edge, and not the flat end of the hammer head, would hit the metal. After half a dozen blows, the silver again flew out from the pliers, this time hitting me in the head. Hammering had always looked very easy. As I had watched smiths at work, I had realized that it was tiring work and that it took a certain amount of strength, but I thought there was no trick to it. One just pounded.

Before that first day was over, I learned that **there is a great deal of skill in hammering properly**. One doesn't just pound. Ever stroke has to be directed. If he does not hammer evenly, the silver spreads more at one place than at another, and twice as much time [75] and effort is spent in trying to get the bar back into shape. Holding the silver with the pliers is most difficult at first. With every blow there is a jar on the hand in which the pliers are held. This sets the beginner on edge. If he grips the silver too insert_drive_file73-76 4 tightly, he tries himself out, mars the metal where the tool grips, and does not allow sufficient ‘give,’ a failure which causes the metal to fly out of the pliers. If he does not hold it tightly enough, the metal flies out anyway. Only experience teaches just how hard to grip the silver."

"Tom Burnsides had agreed to teach me how to work silver, so one morning I arrived at his hogan ready to start work. When he wanted to know what I would like to make, I asked him what would be best for a beginner, and he advised me to make a bracelet. Then he asked me whether I wanted to begin with silver or learn first how to work copper or lead. **He said that many Navajo smiths worked at copper or lead before they started on silver, because those metals were cheaper and easier to work.** When I told him that I wanted the feel of working silver, he gave me one and one-half slugs and told me to melt them. I placed the silver in the crucible and lighted the torch. Tom said that a small amount of silver may be melted with the torch; the forge is usually used only when melting three or more slugs at a time. I held the muzzle of the torch, slanting at an angle, to one side of the crucible; but Tom told me that the torch should be held above the crucible so that the heat would spread evenly over the whole surface of the silver. Then he placed the ingot mold near the crucible, propping it up against a tool, explaining again that the mold must be hot when the silver is poured in, or the metal will cool too rapidly, and crack when it is pounded."

**p79-80** (contexual information)

“There are **individual differences** in the way silversmiths work. In many respects Charlie's work differs from Tom's. While the finished pieces that each makes conform to Navajo traditional patterns, there are differences in their technique. There are differences in the way they handle their tools, in the way they pound the silver, and in the way they melt it. These variations are due to differences in the way the smiths originally learned from their Navajo teachers. Each smith developed his own style of working, and once a pattern was formed, it was adhered to. Muscular co-ordinations became fixed as habits. When Charlie wrapped a piece of wire around two pieces of silver which were to be [80] soldered together, he always held one end of the wire in his mouth, leaving one hand free to hold the silver. Tom never used his mouth, but rested the silver against something while he tried the wire. This is only one of many differences in their working methods. There are probably as many differences in the muscular habits of silversmiths as there are individuals who follow the craft.”

Mitchell, approximately, Rose, & Frisbie, C. J. (2001). Tall woman: the life story of Rose Mitchell, a Navajo woman, c. 1874-1977. University of New Mexico Press. p.204. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=nt13-275

"Of course, **my mother and I were always weaving when we weren't busy doing other things, and we'd tell the girls to sit and watch us. We'd show them how and let them try, too. My mother helped teach Ruth to weave and to respect the loom and all the weaving tools; she taught her to take care of those things properly because that was part of learning to weave, too.**"

# Oceania

## Melanesia

### Kapauku

Pospisil, L. J. (1958). Kapauku Papuans and their law. In Yale University publications in anthropology (Issue 54, pp. 296, plates). Published for the Dept. Anthropology, Yale University. p.40-41. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=oj29-001

"**Approximately at his seventh birthday, he experiences a radical change in the educational efforts of his parents, who start to focus upon transforming this female like individual into a male**. Now the little boy is invited by his father to spend the night in the men’s room. In the beginning, the boy sleeps a few nights with the father and then returns to the mother’s quarters. As time goes on, he sleeps more and more often with his father. Finally, spending the night with the mother becomes the exception to the rule. Also, he eats with the menfolk of the household, gets a stronger bow from his father, and abandons the fishing net. His apron is exchanged for a small “ koteka, a penis sheath,” made of a long gourd held in position by a string which goes around the waist of the little body. Then, wearing the garments that adult Kapauku use, the boy is teased into more prudishness in the presence of women.

At this time the mother’s command vanishes and for it is substituted more intensive control by the father. He scolds more severely and even uses a stick to make the son obey. Nonetheless, the punishment is never harsh. The father is usually lenient with his son, and it is primarily the child’s love, respect, and admiration for the parent which are the stimuli for the boy’s education. The child’s training is never over-intensified and is more sporadic than constant. Often it depends on the boy whether he will follow the parent to the field where he will be taught to clear the underbrush, to cut trees, and build fences. Every now and then insert_drive_file41 the father and son will spend an afternoon in discussing the value of different types of currencies, pig raising, current prices of different merchandise, and the way to become rich. These abstract discussions, illustrated by the father’s own experience, are enjoyed by the eagerly listening boy, who is already aware of the importance of economy and wealth. The parent also enjoys these talks which help bolster his own ego. He tells his son about his exploits and success which, because modesty is a value in this culture, he cannot discuss with his male relatives or friends, and which his own wife, if told, would not believe anyway.

The boy is ready to learn the skills his teacher has mastered. **Making bows and arrows, rolling string on the thigh, making nets, roasting gourds for penis sheaths, polishing stone axes and stone knives, and chipping flint by percussion are a few of the many subjects a Kapauku man-in-the-making has to study.** When the opportunity arises and a new house is needed, the boy may learn how to cut trees, to split logs, and to use an ax and two wedges to make planks. He may also be permitted to help with the construction of the house itself. **Jobs requiring great strength are not taught until the boy reaches about fifteen years of age. Then he is shown how to hollow out a huge log with an ax and shape it into a canoe, how to smooth the floor of the canoe with the same tool changed into an adz, how to make holes for the long vines which are used for pulling the craft to the lake or river and for mooring it.** It is also at this time that the boy, for the first time, tackles the soil of the valley’s bottom lands to carve out a drainage ditch with a wooden, leaf-shaped, spadelike tool. **Hunting with bow and arrow, setting traps, and cutting up of the animals, though explained by the father, are practiced in the adolescents’ gang in a playful way until the boy becomes an expert in these arts**. During the long evenings the boy listens to myths, legends, and actual history told and discussed by the adult members of the household; thus he acquires the awareness of the time perspective which helps him make sense of his life."

### Kwoma

Whiting, J. W. M. (1941). Becoming a Kwoma: teaching and learning in a New Guinea tribe. Published for the Institute of Human Relations by Yale University Press. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=oj13-001

"**Children watch their parents make tools but do little such work themselves. Boys sometimes help their parents by fetching materials for various utensils, and girls begin netting bags before they reach adolescence, but otherwise toolmaking is restricted to older persons**.

In general, the Kwoma child discovers that it is necessary to work to get food, and learns, in part by observation and in part by participation, the techniques that have been developed in the culture for producing it. He is forced to assume responsibility for some of this work, is allowed to help with insert_drive_file48 other tasks if he wishes, and is definitely debarred from still others. Although this work is directed toward the satisfaction of hunger, the children cannot always appreciate this and must be coerced. **A Kwoma does not take full responsibility for many of the tasks until adolescence**; then he learns by experience that no work means no food. The coercion, as we have seen, consists in scolding or beating the child for not doing the tasks expected of him, and in warning him of the dire consequences which follow an undesired act."

### Trobriands

Scoditti, G. M. G. (1989). Kitawa: a linguistic and aesthetic analysis of visual art in Melanesia. In Approaches to semiotics (pp. viii, 457). Mouton de Gruyter. p.46-48. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=ol06-032

"**After initiation, a child goes to stay with his initiator, in his hut, sometimes in another village if the carver lives in a region different from that of the pupil. He is adopted by the carver**; that virtually means the child's separation from his parents, brothers and sisters, as well as from his peers. His relationship with his parents becomes very weak, especially at the beginning of his new life. For example, during 1973-74 and between June and December 1976, one of the sons of Mesiboda Wakuwa, who lives in Kumwageiya village and belongs to the Malasi clan and susupi sub-clan, Mwabei Kaikuyawa (who had been initiated by his paternal uncle, Mwagula Wakuwa) had visited his parents just a couple of times, even though his new village, Kodeuli, is not very far from Kumwageiya, only about twenty minutes walk away.

Even if an initiate stays in the same village where he was born, he lives separate from the other members of his own family and from his peers. In fact, while the majority of the inhabitants of a village go to the gardens (cf. Malinowski 1935) the initiator and the initiate usually stay in their hut, on the veranda, which is a sort of workshop, and spend most of their time carving.

**The veranda of the carver's hut** is one of the points where the inhabitants of a insert_drive_file47 village gather when they come back from the gardens to watch the work of the carver and his initiate. Anyone who wishes to see how the lagimu of a master carver ( tokabitamu bougwa ) or a simple carver ( tokabitamu ) is progressing, or who wishes to know about the work of the initiate, knows where to go. Sometimes the comments made by a commoner are appreciated, especially if he is a kula man (one who takes part in the ritual performances of the kula cf. Malinowski 1922) who can appreciate better than others the artistic qualities of the prowboards.

The veranda of the hut of a carver is a privileged place where the group of the carvers, especially the best carvers of Kitawa, meet in order to comment on the latest work of one of them, as well as on the small models of lagimu or tabuya made by one of the pupils. An initiate can learn much from these comments and criticisms, especially from the technical viewpoint.

During the first years of the apprenticeship the parents of the initiate continue to bring gifts, such as betel nuts, fish, pork, yam and tobacco, to the initiator of their son. But the food offered to him must not be eaten by the apprentice. After two or three years, depending on the age at which the child was initiated, the apprentice sometimes works in the garden of his teacher and goes to fish, or to pick coconuts and bananas for him. The behaviour of the initiate during this period is very important and is subject to the control of the teacher in the sense that if the apprentice reveals a generous nature, the carver will teach him the technique of carving as well as some aesthetic devices for better achieving certain effects. When a carver teaches his art not only to his favourite pupil ( yobweiri ) but also to other pupils, one of them may surpass the other in generosity. For example, Towitara told me that Pilimoni and Gumaligisa had received a good training from him because both of them were very generous in bringing him gifts, even though he had favoured Gumaligisa because of his superior skill. On the other hand, one of Towitara's nephews, the above-mentioned Toganiu, although initiated by him (because he is a son of one of Towitara's sisters), had a defective training because he was judged to be rather mean. So, during the apprenticeship the pupils compete within the same workshop, or school of carving, for the best training. When an initiate starts his training he belongs to the workshop of his master, which is quite different from the workshop of another carver, even if all of them are in the same village. A workshop is formed by the group of pupils of one of the tokabitamu , especially a tokabitamu bougwa , of Kitawa. Its organization recalls the medieval workshop, where a master of art was helped in his work by a group of apprentices whom he taught how to pierce, to carve or to paint and, initially, the first elementary rules of his profession. On Kitawa a pupil who belongs to one of the workshops must help his initiator-master to shape the framework of a lagimu or tabuya and finish off the graphic signs carved on the wood surface, as well as to collect the pigments used to paint the prowboards of the kula canoe, and help his master to colour them, and so on.

**In short, during the first years of his apprenticeship an initiate learns the basic insert_drive_file48 rules of carving, as well as the terminology of the tools of the profession, and he does all the small jobs which in a medieval workshop were done by the helper of a Maestro d'arte.**"

**p52** (contexual information)

To sum up, in his apprenticeship the initiate learns to organize the graphic signs on a wood surface which has been cut in a given shape, while the symbolic meaning, that is, the content of the entire surface as well as of the single graphic sign, is not the focus of his training. And this confirms that what an apprentice should learn is the control of the ‘grammar’ of the abstract composition only. In fact few initiates or carvers know precisely what lagimu means, and all the carvers of Kitawa recognize that when we talk about that subject we enter into the field of suppositions and probabilities (cf. Siyakwakwa's statements C.SS, 75 -- C.SS, 77. -- C.SS, 83). A good carver is judged on the basis of his technical and aesthetic ability.

**p56** (contexual information)

According to Tonori, Towitara and Siyakwakwa an initiate becomes a tokabitamu when he carves a life-size lagimu and/or tabuya, or a real kula canoe, i.e. **after fifteen to twenty years of apprenticeship**, during which he has followed the norms imposed on him by his teacher-initiator, including the respect of taboos. Siyakwakwa, answering the ethnographer, who had asked him when a pupil is insert_drive_file57 judged a carver, replies: ‘When you know how to carve two, three or four lagimu well, and know how to carve the canoe for the kula, only then will you be a real carver.’ (A.SS, 454).

## Polynesia

### Maori

Firth, R. (1959). Economics of the New Zealand Maori. R. E. Owen, Govt.Printer. p.189-190. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=oz04-004

"The games and pursuits of children were often in mimicry of the activities of their parents or, again, were of a competitive, sporting nature. These were encouraged by the elders as tending in the former case to make children familiar with the occupations of later life, and, in the latter, to develop those qualities which would be most useful to them in dealing with their somewhat stern natural and social environment. Provision was also made to promote the knowledge of useful crafts among the boys and girls. **Thus a certain stone named kohurau was used only for making adzes for children and young people, so that by handling them they might learn the use of proper tools. The adzes for workmen were never made from this material.**

**As they grew up boys were initiated by their father into the technique of the various crafts and the magical regulations pertaining thereto, while girls were taught weaving and the kindred arts**. Boys also accompanied their father on bird-snaring or rat-trapping expeditions, and were trained by him in economic lore. Opportunity was also taken on these occasions to instruct the youths in a knowledge of tribal boundaries, family lands, fishing rocks, birding trees, and other points of ownership.

Perhaps the most important branch of education was that of the Whare wananga or “House of Learning”. Here in the winter months a few of the young men of high rank, approved intelligence, and tested powers of memory assembled to receive instruction in tribal history, legends, and genealogies, in the most sacred mythological tales and religious rites, and also, perchance, in the formulae of black magic, by which men were sent down to destruction. Thus, under the strictist conditions of tapu, and hedged in by the most solemn ceremonies, were the traditions of the tribe handed on from one generation of experts to the next. Instruction of a less sacred character was given to larger audiences in such subjects as astronomy, agriculture, fishing, and the like, which would help to fit the young men for their future responsibilities. On account of each of these subjects being termed a whare (house), it has sometimes been thought that a separate house was built insert_drive_file190 for each course of instruction, but such was not the usual practice. They represented merely different curricula, and were given in the one building. The names of the courses and the procedure in connection with the House of Learning varied in different tribes. The importance of this institution in the transmission of culture is indicated by the ideal of the teaching. Says Best: “The object of the School of Learning was to preserve all desirable knowledge pertaining to the subjects already mentioned, and other traditional lore, and to hand it down the centuries free of any alteration, omission, interpolation, or deterioration” (op. cit., 7). Any departure from old teaching was strongly disapproved of, and a slip in the imparting of knowledge might involve the death of the expert, slain by the power of the outraged gods.

The industrial education of the Maori really comprised instruction in three branches; in economic lore, in technique, and in magic. Each was deemed indispensable to the training of the expert in any branch of work. At the same time there was inculcated in him a recognition of the value of labour."

Buck, P. H. (1952). The coming of the Maori. Maori Purposes Fund Board; [distributed by] Whitcombe and Tombs. p. 361-362. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=oz04-003

"During the teen years, the boys and girls were able to assist their parents in manual tasks. The boys assisted their fathers in obtaining material, house building, fishing, fowling, food cultivation, and other masculine activities. **The girls were taught by their female relatives to plait mats and baskets, weave, and prepare food. The development of extra skill was a matter of individual aptitude**.

**To become a master craftsman in the more skilled crafts such as wood carving and tattooing, the adolescent had to be taught by an expert. His apprenticeship was preceded by an initiation ceremony, in which the ritual brought him under the favour of the tutelary god of the particular craft.** The student's understanding was thereby quickened, his ears became receptive to instruction, his memory retentive, and his hands skilful. The arrangements were usually made by the elders but sometimes the keen desire of a boy was recognized by a craftsman. Hori Pukehika of Whanganui told me how he became a master builder and carver. When the carved house of the Takarangi family, named Te Pakū, was being built at Putiki, Hori, as a boy, watched the carvers at work. The head carver was working on the tekoteko human figure to surmount the front gable end when the call came for the midday meal. Hori had been watching with longing eyes, and as the carver had left his chisel and mallet beside the work, he picked them up and commenced to carve the tattoo lines on the unfinished side of the face. He became so engrossed that he did not hear the craftsman return. He was surprised by an exclamation, and raising his head, he saw the head carver gazing with interest and surprise at what he had done. Hori dropped the tools in fear, but the old man looked at him kindly and asked, “Would you really like to learn to carve?” “Yes,” replied the boy. “Very well,” said the kindly expert, “meet me over there on the bank of the river just before sunset.” At the place and time appointed, the old man told Hori to strip and, removing his own clothes, they waded out into insert_drive_file362 the water to waist depth. Just as the sun was setting, the master carver recited a ritual chant, sprinkled the boy with water, and Hori became an entered apprentice in the exclusive guild of builders and carvers. Hori said, “If you look at the tekoteko on Te Pakū, you will notice that on one side of the face, the lines are not quite regular.” Then with a deprecating smile, he added, “The crooked lines are mine.”

**The highest craft among women was weaving and, here again, some were initiated so as to attain the greatest skill.** Tira, the wife of Hori Pukehika, was one of the best weavers in the Whanganui district. After she learned the elements of the craft, the officiating priest told her to weave a rough sampler as an offering. This was laid by the priest on a tapu place termed a tuahu. He then lit a fire and warmed some puha leaves (Sonchus asper) over the embers. Then, with a ritual chant, he gave her the cooked leaves to eat. The ceremony fixed the knowledge she had already acquired and opened her mind and fingers to further skill. Her skill was unquestionable, for as Hori said with a proud smile, she had been “fed”."

# South America

## Amazon and Orinoco

### Pume

Petrullo, V. (1939). The Yaruros of the Capanaparo River, Venezuela. In Bulletin (pp. 161-290 , 14 plates). U.S. Govt Print. Off. p.202. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=ss19-001

"Hunting and fishing are male occupations exclusively. **As soon as the young boy is able to toddle about he is made to play with bow and arrow and learns to make these indispensable tools. It is a common sight to see little boys who are too young to be taken along by the men on hunting expeditions playing at the game of hunting; and when a man is in camp busily preparing his hunting equipment his young son is by his side working industriously on miniature bows and arrows.**

The equipment of the hunter is simple. Bow, arrow, and canoe are indispensable. A Yaruro does not like to roam on land, but there is no need for him to do so since he can get his game in the water-courses or along their banks. So he sets off in the early morning, generally accompanied by his hunting companion, to look for crocodile (Crocodilus babu). He will hunt for other forms of life only reluctantly, having a special liking for crocodile meat."

Leeds, A. (1962). Ecological determinants of chieftainship among the Yaruro Indians of Venezuela. In Akten des 34. Internationalen Amerikanistenkongresses (pp. 597–608). Verlag Ferdinand Berger. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=ss19-003

**p. 606 (contexual information)**

"One more point may be made regarding the ecology as limiter of chieftainship among the Yaruro. **The tools, techniques, and resources require no very extensive, highly specialized or esoteric knowledge. In fact any man or woman, and any child as well, has access to such knowledge, and it is easily acquired by all members of the society who thus have, at least potentially, equal access to control over the means of life. There is no specialized knowledge, at least with respect to technology and habitat, which requires a specialized repository in the form of a chief or learned person.** Yaruro knowledge, itself dependent upon the inventory of tools, techniques, and resources, inhibits any tendency towards the development of any sort of specialists in technical or managerial knowledge. As one might expect, there are no true specialists in Yaruro society. Here and there women make pots and certain women seem to have a special bent for making woven sacks but these are not properly specialities. Nor, from a technological or ecological point of view, is male or female shamanism in any way a speciality. They do not appear to be specialists even in esoteric knowledge. Knowledge of the general type described here might be called ‘dispersive’ or ‘egalitarian’ since it tends to become more or less uniformly distributed among the members of the society. A consequence of the existence of this type of knowledge, associated with the kind of technology described, is that there will be no specialised training of any specialists and, of course, no specialised personnel to do such training. This is the situation which obtains among the Yaruro both with respect to technical and managerial activities. Thus, in Yaruro knowledge, there is no source for the support of an institutionalized and strong chieftainship."

### Warao

Wilbert, J. (1976). To become a maker of canoes: an essay in Warao enculturation. In enculturation in latin america: an anthology: Vol. v. 37 (pp. 303–358). UCLA Latin American Center Publications, University of California. p. 323. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=ss18-021

"This work is carried out within the confines of the village and the children have been watching the craftsman for weeks. The boys are called frequently to the site to observe the process, although they are not permitted to touch the tools, not only to forestall the child's damaging the hull but also to avoid provoking the spirit of the tool. Only men from neburatu up may pick up an adze. **Thus, at least for the child, to learn how to handle the adze and how to finish the hull of a dugout is to learn through observation, never through practice. The adolescent will have to learn later under the guidance of his father. Again there is not much verbal instruction between father and son, but the father does correct the hand of his son and does teach him how to overcome the pain in his wrist from working with the adze.** Another piece of explicit instruction occurs with respect to using the outspread hands to measure the thickness of the hull. The father remeasures the area that his son completes and, if necessary, corrects him personally.

## Southern South America

### Tehuelche

Adem, T. A. (2009). Culture summary: Tehuelche. HRAF. p. 3. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=sh05-000

"Tehuelche children were indulged and seldom corrected by their parents (Cooper, 1946:30). Women were primarily responsible for taking care of children. Other relatives and band members also recognized each child by participating in a variety of ceremonies marking the passage of the child through different developmental stages. Children learned about religious beliefs and social norms by participating in these ceremonies from earliest childhood. Children also learned other practical skills including hunting, gathering, weaving and tool making, from parents and band members."

### Yahgan

Gusinde, M., & Schütze, F. (1937). The Yahgan: the life and thought of the water nomads of Cape Horn. In Die Feuerland-Indianer [The Fuegian Indians]: Vol. Vol. II (p. HRAF: xv, 1471  [incomplete] [original: 365-1185, 1278-1499  ]). Anthropos-Bibliothek. p.563. https://ehrafworldcultures-yale-edu.proxy.library.emory.edu/document?id=sh06-001

"186. Despite some shortcomings in the following description, Bridges affirms that children are given definite instruction by parents and adults: “**Parents universally take no pains in the education of their children, and give them no instruction in the arts of native life, save it may be a little instruction in swimming and basket-making by mothers to their daughters; yet I believe that even for this they are generally as much indebted to others as to their mothers.** The children learn to speak, to use the spear, sling and arrow, to make these and other implements and vessels as best they can” /cited in English/ (MM:IX, 214;1875)."

