---
title: "How do people in non-industrial societies learn to make tools?"
author: "Cheng Liu"
date: "`r Sys.Date()`"
fontsize: 11pt
output: bookdown::pdf_document2
header-includes:
   - \usepackage{textcomp}
   - \usepackage{utopia}
   - \usepackage{lineno}
   - \usepackage{float}
   - \floatplacement{figure}{H}
   - \usepackage{caption}
   - \captionsetup[figure]{font=scriptsize}
   - \captionsetup[table]{font=scriptsize}
linestretch: 1.5
link-citations: yes
linkcolor: blue
bibliography: bibliography.bib
csl: apa.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Research Question

1.  Do hunter-gatherers have a unique learning pattern compared with groups practicing other types of subsistence strategies?

2.  Do learning strategies change across different developmental periods? (More specific hypothesis: will the frequency of social learning decrease through time?)

3.  What are some major transmission biases involved? (kin-based? context(success)-based?)

# Motivation/Significance

1.  At the most basic level, this study provides the most in-depth descriptive investigation on this topic so far.

2.  It can help improving the external validity of archaeological experimental design.

3.  It can serve as a middle-range framework to better understand the formation of archaeological records.

# Data sources and searching strategies

0.  Scope of study: Global sample

1.  EHRAF World Cultures: subject "transmission of skills" + key word "tool". This combination yields ~~133 paragraphs in 96 documents across 72 cultures~~. Another keywords include ~~make (983 paragraphs in 463 documents across 208 cultures)/made (757 paragraphs in 417 documents across 203 cultures)/making (476 paragraphs in 296 documents across 169 cultures)~~, ~~produce (77 paragraphs in 65 documents across 55 cultures)/producing (30 paragraphs in 25 documents across 24 cultures )~~, ~~manufacture (59 paragraphs in 48 documents across 43 cultures)/ manufacturing (5 paragraphs in 5 documents across 5 cultures)~~, ~~create (39 paragraphs in 33 documents across 30 cultures)/ creating (8 paragraphs in 8 documents across 8 cultures)~~, ~~construct (16 paragraphs in 14 documents across 12 cultures)/ constructing (21 paragraphs in 20 documents across 19 cultures )~~, ~~assemble (11 paragraphs in 11 documents across 11 cultures)/ assembling (2 paragraphs in 2 documents across 2 cultures)~~, ~~fabricate (3 paragraphs in 3 documents across 3 cultures)/ fabricating (1 paragraphs in 1 documents across 1 cultures)~~, ~~shape (71 paragraphs in 58 documents across 50 cultures)/ shaping (18 paragraphs in 17 documents across 17 cultures)~~, ~~forge (6 paragraphs in 11 documents across 9 cultures)/ forging (6 paragraphs in 6 documents across 5 cultures)~~, ~~form (324 paragraphs in 198 documents across 133 cultures)/ forming (15 paragraphs in 15 documents across 14 cultures)~~.


5. Exclusion criteria: cases of tool use, commercial economy, instance where local people taught the ethnographer how to make tools, instances where it was clearly stated a new form of government-initiated school to save a certain craft, instances where individuals are taught how to make Christianity-related artifacts such altar, and instances where indigenous people mentioned that they learn a specific craft from museum pieces, photographs. However, they may appear as contextual information in the appendix to provide more details of the technologies themselves. archaeological and historical literatures are also excluded. 

# Variables

*Important Note: "NA" is used in all variables when there is not enough information to make the relevant inference, which is different from absence.*

1.  **Area**: using eHRAF's classification system

2.  **Society**: using eHRAF's classification system

3.  **OWC Code**: The Outline of World Cultures (OWC) is a classification system of the cultures of the world, which is used by eHRAF to organize its databases.

4.  **Subsistence**: This variable follows eHRAF's classification system, including Hunter-gatherer, primarily hunter-gatherer, horticulturalist, agro-pastarolist, intensive agriculturalist, other subsistence combinations. The category of commercial economy is excluded.

5.  **Year of observation**: The years when the given society was observed by the ethnographers. This information is readily available under the name "field date" in the meta information of eHRAF World Cultures.

6.  **Location**: The location where the learning event happens according to the ethnographer's description.

7.  **Location (type)**: [1) *indoor*]{.underline}*:* learning happens inside a building; [2) *outdoor settlement*]{.underline}*:* learning happens inside the settlement but outside the buildings; [3) *outdoor field*]{.underline}: learning happens outside the settlement

8.  **Age of learner**: The learner's age according to the ethnographer's description.

9.  **Age group of learner**: [1) *Infancy*]{.underline} (0-4 years old), [2) *Early Childhood*]{.underline} (4-8 years old), [3) *Middle Childhood*]{.underline} (8-12 years old), [4) *Adolescence*]{.underline}(12-16 years old), [5) *Adult*]{.underline} (\>16 years old). For analytical purpose, this category does not concern the cultural differences on the perception of developmental differences.

10. **Number of learner**: The number of learner according to the ethnographer's description.

11. **Age of model**: The model's age according to the ethnographer's description.

12. **Age group of model**: [1) *Infancy*]{.underline} (0-4 years old), [2) *Early Childhood*]{.underline} (4-8 years old), [3) *Middle Childhood*]{.underline} (8-12 years old), [4) *Adolescence*]{.underline}(12-16 years old), [5) *Adult*]{.underline} (\>16 years old). For analytical purpose, this category does not concern the cultural differences on the perception of developmental differences.

13. **Number of model**: The number of model according to the ethnographer's description.

14. **Transmission modes**: [1) *horizontal transmission*]{.underline}: social learning from individuals of the same generation, age group, or cohort, roughly within 4--5 years of age; [2) *vertical transmission*]{.underline}: children learning from their parents; [3) *oblique transmission*]{.underline}: social learning between individuals of distinct generations or age groups typically from an older generation to a younger generation. It can happen within or beyond extended kin group, such as learning from grandparents, uncles, or other adults in the local population; [4) *mixed*]{.underline}: different transmission modes occurred together in the learning process of a given technology.

15. **Social relationship**: The relationship between the learner and the model according to the ethnographer's description. For example, mother-son/father-daughter/etc.

16. **Transmission bias**: This category follows the framework developed by Kendal at al. (2018). [1) *kin-based bias*]{.underline}: learning a cultural trait from people who are your kin members, [2) *success-based bias*]{.underline}: learning a cultural trait from people because they are successful in this technology, [3) *prestige-based bias*]{.underline}: learning a cultural trait from people because of their high social status; [4) *conformist bias*]{.underline}: learning a specific type of knowledge from other people because it is displayed by the majority of local population; [5) *mixed*]{.underline}: different transmission biases occurred together in the learning process of a given technology.

17. **Learning processes**: This category follows the framework developed by Garfield et al. (2016). [1) *imitation/emulation*]{.underline}: The learner directly observes some skill or behavior and attempts to replicate the observed actions or behaviors; [2) *local enhancement*]{.underline}: The learner gains knowledge or skills by interacting with the local environment because other individuals expose the learner to the setting or environment (e.g., parents take children gathering or walk through forest); [3) *stimulus enhancement*]{.underline}: The learner is given an object to facilitate learning how to use the object; [4) *collective learning*]{.underline}: Individuals of approximately equal age, skill, knowledge, and cognitive ability collectively contribute to the learning of a specific skill or knowledge; [5) *collective learning play*]{.underline}: Type of collaborative learning that involves the transmission, acquisition, or practice of cultural knowledge or skills through informal play or miscellaneous games; [6) *collective learning role play*]{.underline}: Type of collaborative learning that involves individuals of similar age collectively playing social roles (e.g., play house, husband-wife); [7) *teaching*]{.underline}: An individual modifies his or her behavior specifically to impart knowledge, skills, or behaviors, to a learner, but there is insufficient information to code as demonstration or storytelling; [8) *teaching demonstration*]{.underline}: Type of teaching where an individual demonstrates knowledge, skills, or behaviors, to a learner, and may offer feedback and examples during the process; [9) *teaching storytelling*]{.underline}: Type of teaching where an individual actively imparts specific (within one of the defined domains) knowledge, skills, or behaviors to a learner by verbal communication of stories or metaphors; [10) *individual learning*]{.underline}: Individual exhibits repeated attempts to learn a skill or develop new skills or knowledge on his or her own, including trial and error and individual practice; [11) *mixed*]{.underline}: different learning processes occurred together in the learning context of a given technology.

18. **Time spent**: The time spent on learning according to the ethnographer's description.

19. **Time spent (type)**: [1) *one-shot learning*]{.underline}: the learners only need to learn once to acquire a given technology. [2) *repeated learning*]{.underline}: the learners need to multiple time, including individual trial-and-error learning and practice, to acquire a given technology.

20. **Technology**: The subject of learning according to the ethnographer's description.

21. **Raw material**: stone, clay, plant, bones, etc.

22. **Restriction of status involved**: The restriction on the social status involved in the learning according to the ethnographer's description. For example, gender, wealth, religious status.

23. **Note** (habit, context, difficulty perceived by local people and ethnographers, access to raw material)

24. **Reference**

# Dissucusion points

1. Protracted and staged learning period

2. The distribution of expertise

3. Co-production as a way of teaching toolmaking

4. Skill training as a byproduct

# Acknowledgement

This work was assisted in part by skills learned at the 2022 NSF HRAF Summer Institute for Cross Cultural Anthropological Research (NSF BCS Grant #2020156 to HRAF). I would also like to thank Carol Ember, Fiana Jordan, and Sean Roberts for their comments on the research design of this project.

